"""Build a portable local report from saved measurements; never rerank models."""
import base64
import csv
import html
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'results/accuracy_calibration'
def read(name): return list(csv.DictReader((OUT/name).open(encoding='utf-8')))
def pct(r,key='accuracy'): return f'{100*float(r[key]):.2f}%'
def table(head,rows):
    return '<table><thead><tr>'+''.join(f'<th>{html.escape(str(x))}</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{html.escape(str(x))}</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table>'
def image(name):
    return '<img alt="'+html.escape(name.replace('_',' '))+'" src="data:image/png;base64,'+base64.b64encode((OUT/name).read_bytes()).decode()+'">'

def main():
    train=read('nested_training_cv.csv'); test=read('exploratory_test_accuracy.csv'); legacy=read('baseline_reproduction.csv'); curves=read('calibration_curves.csv'); transfer=read('pre_post_transfer.csv')
    sessions=[r['session'] for r in legacy]
    parts=['''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>G27 accuracy and calibration</title><style>body{font:16px/1.55 system-ui,sans-serif;color:#18232b;max-width:1120px;margin:40px auto;padding:0 24px}h1{font-size:32px;line-height:1.2}h2{font-size:24px;margin-top:38px}p{max-width:960px}table{border-collapse:collapse;width:100%;font-size:14px;margin:18px 0}th,td{text-align:right;padding:9px 11px;border-bottom:1px solid #d8dfe4}th:first-child,td:first-child{text-align:left}th{background:#f3f6f7}img{width:100%;height:auto}a{color:#176b91}.note{border-left:3px solid #176b91;padding-left:18px}small{color:#53616a}@media(max-width:700px){body{margin:20px auto;padding:0 12px}table{font-size:12px}th,td{padding:7px 5px}}@media print{body{max-width:none;margin:0}h2{break-after:avoid}table,img{break-inside:avoid}}</style><body><h1>Accuracy and calibration: first bounded comparison</h1><p>4 October 2026 · G27 Stroke Rehab · accuracy track proposed by Anna, as attributed by Jason.</p><p class="note"><strong>The historical result reproduced exactly: 444/479 (92.7%). This pass has not established an improvement over it.</strong> The new training-selected model scored 428/480 (89.2%), against 433/480 (90.2%) for the common causal-window CSP baseline. Riemannian features are the strongest candidate in the training-only comparison. All reused test scores remain exploratory.</p><p>The common comparison uses 80 training and 80 test trials per session, 40 per hand, features from <strong>[2.5,6.5) seconds after the attention trigger</strong>, cue at +2 seconds. Trial-local causal filtering uses only [0,6.5) seconds, with independent filter state per trial. Settings and model families are chosen using training data only.</p>''']
    parts.append('<h2>Reproduction of Anna\'s team baseline</h2><p>Unchanged three-band regularized CSP and shrinkage LDA, selected by five-fold stratified training-run CV, seed27. Continuous zero-phase filtering, [2.5,6.5) s features, 80 training and 80 test trials per session. Every saved result field matches the committed session_results.csv. The new causal models use the same feature window and trial counts, but different filtering and covariance/CSP processing.</p>')
    parts.append(table(['Session','Training trials','Correct/test trials','Accuracy','Matches previous'],[[r['session'],r['train_trials'],r['correct']+'/'+r['trials'],pct(r),r['matches_previous']] for r in legacy]))
    parts.append('<h2>Training-only comparison</h2><p>Outer validation: five chronological 16-trial blocks, one adjacent trial purged on each available side (62–63 fitting trials). Inner setting selection: three stratified folds on those fitting trials. Every transformer is fitted inside its partition. The selected row includes family selection inside each outer loop. Each cell is correct/80; these are training-run out-of-fold predictions.</p>')
    fam=['CSP-baseline','FBCSP','Riemann','TV-CSP','selected']
    lookup={(r['session'],r['family']):r for r in train}
    parts.append(table(['Session']+fam,[[s]+[lookup[s,f]['correct']+'/80' for f in fam] for s in sessions]))
    totals={f:sum(int(r['correct']) for r in train if r['family']==f) for f in fam}
    parts.append('<h3>Accuracy and probability quality differ</h3><p>The Riemannian family leads by classification accuracy. The fixed causal CSP baseline has better mean Brier score and log loss (lower is better). These are descriptive training-run OOF measures, not patient-level uncertainty.</p>')
    parts.append(table(['Pipeline','Correct/480','Mean Brier (lower better)','Mean log loss (lower better)'], [[f,str(totals[f])+'/480',f"{sum(float(r['brier']) for r in train if r['family']==f)/6:.6f}",f"{sum(float(r['log_loss']) for r in train if r['family']==f)/6:.6f}"] for f in ('CSP-baseline','Riemann')]))
    parts.append('<p>Riemannian gains 10 correct trials in P1 PRE and 11 in P2 PRE, ties P1 POST, and loses two in each of the other three sessions. Neither pipeline improves every measure or session. The pipelines also differ in band construction, covariance/CSP processing and classifier; this does not isolate a benefit of Riemannian geometry.</p>')
    parts.append('<p>Riemannian family: <strong>'+str(totals['Riemann'])+'/480 = '+f"{100*totals['Riemann']/480:.2f}%"+'</strong>, compared with '+str(totals['CSP-baseline'])+'/480 for the fixed common baseline and '+str(totals['selected'])+'/480 for the complete selector. Selection is unstable across folds; the per-session selector does not consistently choose the strongest chronological performer. Do not replace its choices with test winners.</p>')
    parts.append('<h2>Exposed-test accuracy</h2><p>One full-training fit per family; settings selected on training data. All cells have 80 test trials and [2.5,6.5) s features. Comparisons with Anna\'s baseline include filtering and covariance differences. All test comparisons are exploratory.</p>')
    lookup={(r['session'],r['family']):r for r in test}
    parts.append(table(['Session','Anna baseline']+fam,[[s,pct(next(r for r in legacy if r['session']==s))]+[pct(lookup[s,f]) for f in fam] for s in sessions]))
    parts.append('<p>The Riemannian family scored 446/480 (92.92%), 13 more correct than Anna\'s reproduced 433/480 (90.21%): an exploratory increase of 2.71 percentage points for the complete pipeline. It also has the strongest training-only family score. Freeze it as a candidate for an untouched run/participant; these exposed tests do not provide fresh held-out validation.</p>')
    parts.append('<h2>Accuracy versus calibration burden</h2><p>0 labels: train on 320 trials from the other two participants; both target-participant sessions and all source test runs are excluded. Select using leave-one-source-participant-out validation. 10/20/40 labels: five nested, balanced target-only subsets, with settings selected within each subset. 80 labels: the frozen full-session choice. These are two different fitting regimes, not a fine-tuning curve. Cross-run pooling assumes channel correspondence; PR #3 raises an unverified layout hypothesis that requires acquisition metadata.</p>')
    lookup={(r['session'],int(r['n_calibration'])):r for r in curves}
    parts.append(table(['Session','0','10','20','40','80'],[[s]+[pct(lookup[s,n]) for n in (0,10,20,40,80)] for s in sessions]))
    parts.append(image('calibration_curves.png'))
    parts.append('<p>The same 80-test-trial run is reused at every point. 10–40 values are means, and bars span the full five-subset range; they are not confidence intervals. Trial indices, per-subset model choices, minimum/maximum and SD are saved. P3 POST ranges from 37.5% to 97.5% at 10 labels, and P2 PRE remains weak: do not claim a universal 10-trial calibration requirement.</p>')
    parts.append('<h2>Probability reliability</h2><p>Descriptive reliability for the full-training selected models. Five fixed bins, with trial counts. No probability calibrator was fitted from test outcomes. P1 POST and P2 PRE illustrate that high confidence can accompany errors.</p>')
    parts.append(table(['Session','Chosen model/setting','Brier score','Log loss'],[[s,lookup_row['chosen_setting'],f"{float(lookup_row['brier']):.3f}",f"{float(lookup_row['log_loss']):.3f}"] for s in sessions for lookup_row in [next(r for r in test if r['session']==s and r['family']=='selected')]]))
    parts.append(image('probability_reliability.png'))
    parts.append('<h2>PRE → POST transfer</h2><p>Use 80 PRE training trials, choose settings on those trials, and score 80 POST test trials. No PRE test labels, POST calibration labels or POST-based selection. This respects temporal direction but remains an exploratory offline replay. Channel identity/order across runs is unverified; a possible layout difference could also impair transfer. Do not attribute these failures solely to session drift.</p>')
    parts.append(table(['Participant','Correct/80','Accuracy','PRE-selected model'],[[r['patient'],r['correct']+'/80',pct(r),r['chosen_setting']] for r in transfer]))
    parts.append('''<h2>What this means for the rehab track</h2><p>The four-second scoring window overlaps nominal feedback from approximately +3.5 s. Causal filtering prevents future-sample contamination but cannot remove cues, stimulation, visual feedback or artifacts already recorded. Three participants, six repeated sessions and absent per-trial feedback/clinical outcome labels do not establish recovery or therapeutic efficacy. The useful handoff is the measured calibration burden, poor transfer cells and a Riemannian candidate for independent evaluation.</p><h2>Organizer scoring and submission</h2><p>The <a href="https://github.com/unicorn-bi/Hackathon#presentation-information">official organizer README</a> requires a video no longer than 2:30, using its template, with G27 visible throughout. Upload to the group's presentation folder by <strong>5 October 2026, 19:30 London (11:30 PDT)</strong>. It does not define a numerical scoring window, metric, trial-exclusion rule or prediction-file schema. The designated questions address is guger@gtec.at. A source-backed inquiry is saved in the Competitions owner folder, unsent under Jason's standing email rule.</p><h2>Reproducibility and checks</h2><p>Nine tests passed. Synthetic perturbations confirm later samples and other trials cannot alter a trial's features. Saved-data checks confirm six legacy matches, 80-trial common denominators, complete OOF coverage, exact 80-label endpoint agreement and 80 reliability-bin observations per session. These establish implementation checks, not scientific or clinical validation.</p><p><a href="../../analysis/accuracy_calibration/PROTOCOL.md">Full protocol</a> · <a href="../../analysis/accuracy_calibration/README.md">Reproduction instructions</a> · <a href="provenance.json">Input/runtime provenance</a> · <a href="validation.json">Validation receipt</a> · <a href="calibration_curves.csv">Calibration CSV</a> · <a href="nested_training_cv.csv">Training comparison CSV</a> · <a href="exploratory_test_accuracy.csv">Test accuracy CSV</a> · <a href="pre_post_transfer.csv">Transfer CSV</a></p><small>Local contribution on codex/accuracy-calibration. No submission or outbound organizer message. The earlier PR #1 was observed closed and unmerged; this pass does not reopen it.</small></body></html>''')
    report='\n'.join(parts)
    report=report.replace('strongest candidate in the training-only comparison', 'strongest candidate by accuracy in the training-only comparison')
    report=report.replace('The historical result reproduced exactly: 444/479 (92.7%). This pass has not established an improvement over it.', 'Anna\'s team baseline reproduced exactly: 433/480 (90.2%). Riemannian features lead training-only accuracy; probability scores favor fixed causal CSP. Their exposed-test score is 446/480 (92.9%).')
    report=report.replace('<h2>What this means for the rehab track</h2>', '<h2>EEG cutoff and delivered latency</h2><p>The new comparison uses EEG only before +6.5 seconds after the attention trigger. Inference, chunk arrival and transport latency were not measured for these models. The six verified local streaming exports are earlier [2.5,3.5) s continuous-filter CSP models from a separate pipeline. No Riemannian streaming export was verified.</p><h2>What this means for the rehab track</h2>')
    report=report.replace('Nine tests passed.', 'The original study recorded 37 passing tests; <a href="../overnight/FINAL_CHECKS.json">the final review-branch receipt</a> records the current suite.').replace('six legacy matches', 'six team-baseline matches')
    report=report.replace('Local contribution on codex/accuracy-calibration.', 'Historical numerical study from codex/accuracy-calibration, now packaged for review.')
    report=report.replace('The earlier PR #1 was observed closed and unmerged; this pass does not reopen it.', 'The original study was based on Anna\'s ffcdb7e snapshot. The current <a href="https://github.com/ZyntZ/gtec-g27-data-stroke/pull/2">draft model/research PR #2</a> incorporates the study on newer main with separate verification receipts. Sudip/nxxis 444/479 is a separately reproduced reference, not the team baseline.')
    (OUT/'REPORT.html').write_text(report,encoding='utf-8')

if __name__=='__main__': main()
